import { StyleSheet } from 'react-native';

import type { useAppTheme } from '../../../theme/themeProvider';
type ThemeColors = ReturnType<typeof useAppTheme>['colors'];

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    headerRow: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    headerCopy: {
      flex: 1,
    },
    headerActions: {
      flexDirection: 'row',
      gap: 8,
      marginLeft: 12,
      marginTop: 4,
    },
    headerButton: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 20,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    overviewCard: {
      marginBottom: 12,
      padding: 16,
    },
    overviewHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 12,
    },
    feedbackIcon: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 17,
      height: 34,
      justifyContent: 'center',
      marginRight: 10,
      width: 34,
    },
    feedbackCopy: {
      flex: 1,
    },
    feedbackTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 3,
    },
    overviewMetrics: {
      flexDirection: 'row',
      gap: 8,
    },
    metricItem: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 15,
      flex: 1,
      paddingHorizontal: 7,
      paddingVertical: 9,
    },
    metricValue: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 4,
      textAlign: 'center',
    },
    metricLabel: {
      color: colors.textMuted,
      fontSize: 11,
      fontWeight: '700',
      marginBottom: 5,
      textAlign: 'center',
    },
    metricTag: {
      alignSelf: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 999,
      color: colors.primaryPressed,
      fontSize: 10,
      fontWeight: '800',
      overflow: 'hidden',
      paddingHorizontal: 7,
      paddingVertical: 3,
      textAlign: 'center',
    },
    reminderPrompt: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 12,
      paddingHorizontal: 14,
      paddingVertical: 13,
    },
    reminderPromptIcon: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 18,
      height: 36,
      justifyContent: 'center',
      marginRight: 11,
      width: 36,
    },
    reminderPromptTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 3,
    },
    reminderPromptText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
    },
    reminderPromptCta: {
      backgroundColor: colors.surfaceMuted,
      borderRadius: 999,
      marginLeft: 10,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    reminderPromptCtaText: {
      color: colors.privacy,
      fontSize: 12,
      fontWeight: '800',
    },
    teamHomeCard: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 12,
      padding: 14,
    },
    teamHomeCopy: {
      flex: 1,
      marginRight: 10,
    },
    teamHomeDescription: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
    },
    teamHomeIcon: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderRadius: 19,
      height: 38,
      justifyContent: 'center',
      marginRight: 12,
      width: 38,
    },
    teamHomePill: {
      backgroundColor: colors.primarySoft,
      borderRadius: 999,
      color: colors.primaryPressed,
      flexShrink: 0,
      fontSize: 11,
      fontWeight: '800',
      overflow: 'hidden',
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    teamHomeTitle: {
      color: colors.text,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '900',
      marginRight: 8,
    },
    teamHomeTitleRow: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 4,
    },
    heroCard: {
      borderRadius: 24,
      marginBottom: 12,
      padding: 18,
    },
    heroTop: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 14,
    },
    heroCopy: {
      flex: 1,
      marginRight: 14,
    },
    heroTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      marginBottom: 6,
    },
    mutedText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 20,
    },
    ringOuter: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 34,
      height: 68,
      justifyContent: 'center',
      width: 68,
    },
    ringInner: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 27,
      height: 54,
      justifyContent: 'center',
      width: 54,
    },
    actionRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 20,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 12,
      padding: 14,
    },
    rowIcon: {
      alignItems: 'center',
      borderRadius: 19,
      height: 38,
      justifyContent: 'center',
      marginRight: 12,
      width: 38,
    },
    infoBadge: {
      backgroundColor: colors.infoSoft,
    },
    rowCopy: {
      flex: 1,
    },
    rowTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 3,
    },
    toolCard: {
      marginTop: 12,
      padding: 6,
    },
    utilityRow: {
      alignItems: 'center',
      flexDirection: 'row',
      minHeight: 58,
      paddingHorizontal: 8,
      paddingVertical: 10,
    },
    utilityIcon: {
      alignItems: 'center',
      borderRadius: 17,
      height: 34,
      justifyContent: 'center',
      marginRight: 10,
      width: 34,
    },
    utilityTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      marginBottom: 3,
    },
    utilityText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
    },
    toolDivider: {
      backgroundColor: colors.border,
      height: 1,
      marginHorizontal: 8,
    },
  });
}
