export const routes = {
  habits: '/habits',
  home: '/',
  me: '/me',
  meProfile: '/me/profile',
  nudgeChat: (userId: string) => `/nudges/${encodeURIComponent(userId)}`,
  pro: '/pro',
  reminders: '/reminders',
  safety: '/safety',
  settings: '/settings',
  team: '/team',
  teamInvite: '/team/invite',
  teamSettings: '/team/settings',
  toilet: '/toilet',
  toiletComplete: '/toilet/complete',
  toiletRecord: (id: string) => `/toilet/records/${encodeURIComponent(id)}`,
  trends: '/trends',
  advancedReport: '/trends/advanced',
  training: '/training',
  trainingComplete: '/training/complete',
  trainingSession: '/training/session',
  watch: '/watch',
} as const;
