export const routes = {
  habits: '/habits',
  home: '/',
  friend: (userId: string) => `/friends/${encodeURIComponent(userId)}`,
  friendEvents: (userId: string) => `/friends/${encodeURIComponent(userId)}/events`,
  friendInvite: '/friends/invite',
  friendJoin: (token: string) => `/friend/join/${encodeURIComponent(token)}`,
  friends: '/friends',
  me: '/me',
  meProfile: '/me/profile',
  pro: '/pro',
  reminders: '/reminders',
  safety: '/safety',
  settings: '/settings',
  toilet: '/toilet',
  toiletComplete: '/toilet/complete',
  toiletRecord: (id: string) => `/toilet/records/${encodeURIComponent(id)}`,
  trends: '/trends',
  advancedReport: '/trends/advanced',
  training: '/training',
  trainingComplete: '/training/complete',
  trainingSession: '/training/session',
  watch: '/watch',
} as const;
