import { StyleSheet } from 'react-native';

import type { useAppTheme } from '../../../theme/themeProvider';
type ThemeColors = ReturnType<typeof useAppTheme>['colors'];

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    feedbackCard: {
      alignItems: 'center',
      flexDirection: 'row',
      marginBottom: 18,
    },
    feedbackIcon: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 22,
      height: 44,
      justifyContent: 'center',
      marginRight: 13,
      width: 44,
    },
    feedbackCopy: {
      flex: 1,
    },
    feedbackTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '800',
      marginBottom: 5,
    },
    mutedText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '500',
      lineHeight: 20,
    },
    emptyCard: {
      marginBottom: 20,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '800',
      marginBottom: 6,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 12,
      marginTop: 4,
    },
    legendDot: {
      borderRadius: 4,
      height: 8,
      width: 8,
    },
    legendItem: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 5,
    },
    legendText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 16,
    },
    summaryTile: {
      backgroundColor: colors.surface,
      borderRadius: 18,
      borderWidth: 1,
      flexBasis: '47%',
      flexGrow: 1,
      padding: 16,
    },
    summaryValue: {
      fontSize: 22,
      fontWeight: '800',
      marginBottom: 6,
    },
    summaryLabel: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    riskCard: {
      alignItems: 'flex-start',
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
      flexDirection: 'row',
      marginBottom: 16,
    },
    riskText: {
      color: colors.text,
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 20,
      marginLeft: 10,
    },
    proButton: {
      marginTop: 12,
    },
    proCard: {
      gap: 8,
      marginBottom: 16,
    },
    proTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '900',
    },
    weekDayColumn: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      flexBasis: 0,
      flexGrow: 1,
      gap: 8,
      minWidth: 0,
      paddingHorizontal: 2,
      paddingVertical: 9,
    },
    weekDayColumnToday: {
      backgroundColor: colors.surface,
      borderColor: colors.primary,
    },
    weekDayLabel: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '800',
      lineHeight: 13,
      textAlign: 'center',
      width: '100%',
    },
    weekDayLabelToday: {
      color: colors.primaryPressed,
      fontWeight: '900',
    },
    weekDaySignalPanel: {
      alignItems: 'center',
      gap: 6,
      paddingVertical: 2,
    },
    weekFootnote: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
    },
    weekTimeline: {
      flexDirection: 'row',
      gap: 5,
    },
    weekLegendRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    weekNotice: {
      alignItems: 'flex-start',
      backgroundColor: colors.warningSoft,
      borderColor: colors.warning,
      borderRadius: 14,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    weekNoticeText: {
      color: colors.text,
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      lineHeight: 18,
    },
    weeklyCard: {
      gap: 16,
      marginBottom: 18,
      padding: 16,
    },
    weeklyEyebrow: {
      color: colors.textSubtle,
      fontSize: 12,
      fontWeight: '800',
      lineHeight: 15,
      marginBottom: 3,
    },
    weeklyHero: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
    },
    weeklyHeroCopy: {
      flex: 1,
    },
    weeklyRecordBadge: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 16,
      minWidth: 58,
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    weeklyRecordLabel: {
      color: colors.primaryPressed,
      fontSize: 10,
      fontWeight: '800',
      lineHeight: 13,
    },
    weeklyRecordValue: {
      color: colors.primaryPressed,
      fontSize: 17,
      fontWeight: '900',
      lineHeight: 20,
    },
    weeklySummaryIcon: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 11,
      borderWidth: 1,
      height: 24,
      justifyContent: 'center',
      width: 24,
    },
    weeklySummaryLabel: {
      color: colors.textMuted,
      fontSize: 10,
      fontWeight: '700',
      lineHeight: 13,
    },
    weeklySummaryPill: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      flex: 1,
      gap: 5,
      justifyContent: 'center',
      minWidth: 0,
      paddingHorizontal: 8,
      paddingVertical: 9,
    },
    weeklySummaryRow: {
      flexDirection: 'row',
      gap: 8,
    },
    weeklySummaryValue: {
      fontSize: 15,
      fontWeight: '900',
      lineHeight: 18,
    },
    weeklyTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '900',
      marginBottom: 4,
    },
    weekStatusDot: {
      borderRadius: 5,
      height: 10,
      width: 10,
    },
  });
}
