import { StyleSheet } from 'react-native';

import { useAppTheme } from '../../../theme/themeProvider';
import { DURATION_WHEEL_ROW_HEIGHT, DURATION_WHEEL_SIDE_ROWS } from '../toiletRecordForm.constants';

type ThemeColors = ReturnType<typeof useAppTheme>['colors'];

export function createToiletRecordFormStyles(colors: ThemeColors) {
  return StyleSheet.create({
    addSignalChip: {
      alignItems: 'center',
      borderColor: colors.primary,
      borderRadius: 16,
      borderStyle: 'dashed',
      borderWidth: 1,
      flexDirection: 'row',
      minHeight: 42,
      paddingHorizontal: 12,
    },
    addSignalText: {
      color: colors.primaryPressed,
      fontSize: 13,
      fontWeight: '800',
      marginLeft: 4,
    },
    choiceChip: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.border,
      borderRadius: 15,
      borderWidth: 1,
      flexGrow: 1,
      minHeight: 42,
      paddingHorizontal: 10,
      justifyContent: 'center',
    },
    choiceChipSelected: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    choiceChipText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '800',
    },
    choiceChipTextSelected: {
      color: colors.primaryPressed,
    },
    choiceGrid: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 10,
    },
    choiceLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
    },
    customSignalAddButton: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 14,
      justifyContent: 'center',
      minHeight: 44,
      paddingHorizontal: 12,
    },
    customSignalAddText: {
      color: colors.primaryPressed,
      fontSize: 13,
      fontWeight: '800',
    },
    customSignalEditor: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    customSignalInput: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 14,
      borderWidth: 1,
      color: colors.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '600',
      minHeight: 44,
      paddingHorizontal: 12,
    },
    customSignalList: {
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      marginBottom: 18,
      overflow: 'hidden',
    },
    customSignalRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      flexDirection: 'row',
      minHeight: 48,
      paddingHorizontal: 14,
    },
    customSignalRowText: {
      color: colors.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
    },
    detailCard: {
      marginBottom: 18,
      padding: 16,
    },
    detailDivider: {
      backgroundColor: colors.border,
      height: 1,
      marginVertical: 16,
    },
    durationCaption: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 3,
    },
    durationCard: {
      alignItems: 'center',
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    durationEditButton: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.primary,
      borderRadius: 15,
      borderWidth: 1,
      flexDirection: 'row',
      minHeight: 38,
      paddingHorizontal: 11,
    },
    durationEditText: {
      color: colors.primaryPressed,
      fontSize: 13,
      fontWeight: '800',
      marginLeft: 4,
    },
    durationPickerCaption: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '600',
      marginTop: 4,
    },
    durationPickerError: {
      color: colors.danger,
      fontSize: 13,
      fontWeight: '700',
      marginHorizontal: 24,
      marginTop: 12,
      textAlign: 'center',
    },
    durationPickerReadout: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 18,
      marginHorizontal: 24,
      paddingVertical: 14,
    },
    durationSheetContent: {
      gap: 0,
      paddingHorizontal: 0,
    },
    durationPickerValue: {
      color: colors.primaryPressed,
      fontSize: 28,
      fontVariant: ['tabular-nums'],
      fontWeight: '900',
    },
    durationWheelColumn: {
      flex: 1,
    },
    durationWheelContent: {
      paddingVertical: DURATION_WHEEL_ROW_HEIGHT * DURATION_WHEEL_SIDE_ROWS,
    },
    durationWheelItem: {
      alignItems: 'center',
      height: DURATION_WHEEL_ROW_HEIGHT,
      justifyContent: 'center',
    },
    durationWheelLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '800',
      marginBottom: 8,
      textAlign: 'center',
    },
    durationWheelRow: {
      flexDirection: 'row',
      gap: 14,
      paddingHorizontal: 24,
      paddingTop: 20,
    },
    durationWheelSelection: {
      borderBottomColor: colors.primary,
      borderBottomWidth: 1,
      borderTopColor: colors.primary,
      borderTopWidth: 1,
      height: DURATION_WHEEL_ROW_HEIGHT,
      left: 0,
      position: 'absolute',
      right: 0,
      top: DURATION_WHEEL_ROW_HEIGHT * DURATION_WHEEL_SIDE_ROWS,
      zIndex: 1,
    },
    durationWheelValue: {
      color: colors.textSubtle,
      fontSize: 20,
      fontVariant: ['tabular-nums'],
      fontWeight: '700',
    },
    durationWheelValueSelected: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '900',
    },
    durationWheelViewport: {
      height: DURATION_WHEEL_ROW_HEIGHT * (DURATION_WHEEL_SIDE_ROWS * 2 + 1),
      overflow: 'hidden',
    },
    durationValue: {
      color: colors.text,
      fontSize: 24,
      fontVariant: ['tabular-nums'],
      fontWeight: '900',
    },
    feelingChoice: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      flex: 1,
      gap: 7,
      justifyContent: 'center',
      minHeight: 78,
      paddingHorizontal: 6,
    },
    feelingChoiceSelected: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    feelingChoiceText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '800',
    },
    feelingChoiceTextSelected: {
      color: colors.primaryPressed,
    },
    feelingGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 16,
    },
    formError: {
      color: colors.danger,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 19,
      marginBottom: 12,
    },
    groupTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 12,
    },
    helperText: {
      color: colors.textSubtle,
      fontSize: 12,
      fontWeight: '600',
      marginBottom: 16,
    },
    manageButton: {
      minHeight: 34,
      justifyContent: 'center',
      paddingHorizontal: 4,
    },
    manageButtonText: {
      color: colors.primaryPressed,
      fontSize: 13,
      fontWeight: '800',
    },
    pressed: {
      opacity: 0.78,
      transform: [{ scale: 0.98 }],
    },
    priorityChoice: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      flex: 1,
      minHeight: 108,
      padding: 13,
    },
    priorityChoiceCaption: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
      marginTop: 5,
    },
    priorityChoiceSelected: {
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
    },
    priorityChoiceTitle: {
      color: colors.text,
      fontSize: 14,
      fontWeight: '800',
      marginTop: 10,
    },
    priorityChoiceTitleSelected: {
      color: colors.danger,
    },
    priorityGrid: {
      flexDirection: 'row',
      gap: 8,
      marginBottom: 18,
    },
    removeSignalButton: {
      alignItems: 'center',
      flexDirection: 'row',
      minHeight: 36,
      paddingHorizontal: 4,
    },
    removeSignalText: {
      color: colors.danger,
      fontSize: 13,
      fontWeight: '800',
      marginLeft: 4,
    },
    safetyCard: {
      marginBottom: 18,
    },
    safetyCardDanger: {
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
    },
    safetyCardWarning: {
      backgroundColor: colors.warningSoft,
      borderColor: colors.warning,
    },
    safetyHeader: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      marginBottom: 14,
    },
    safetyText: {
      color: colors.text,
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 20,
      marginLeft: 10,
    },
    signalCaption: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 18,
      marginTop: 3,
    },
    signalChip: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 16,
      borderWidth: 1,
      justifyContent: 'center',
      minHeight: 42,
      paddingHorizontal: 12,
    },
    signalChipSelected: {
      backgroundColor: colors.primarySoft,
      borderColor: colors.primary,
    },
    signalChipText: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: '800',
    },
    signalChipTextSelected: {
      color: colors.primaryPressed,
    },
    signalGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    signalHeader: {
      alignItems: 'flex-start',
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    signalHeaderCopy: {
      flex: 1,
      paddingRight: 12,
    },
    sheetContent: {
      gap: 0,
      paddingBottom: 8,
      paddingHorizontal: 24,
    },
    sheetSectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
      marginBottom: 10,
    },
    supplementAction: {
      color: colors.primaryPressed,
      fontSize: 13,
      fontWeight: '800',
      marginLeft: 8,
    },
    supplementActionDanger: {
      color: colors.danger,
    },
    supplementCaption: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: '600',
      marginTop: 4,
    },
    supplementCard: {
      alignItems: 'center',
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.border,
      borderRadius: 18,
      borderWidth: 1,
      flexDirection: 'row',
      marginBottom: 14,
      minHeight: 72,
      paddingHorizontal: 14,
    },
    supplementCardDanger: {
      backgroundColor: colors.dangerSoft,
      borderColor: colors.danger,
    },
    supplementCopy: {
      flex: 1,
      minWidth: 0,
    },
    supplementIcon: {
      alignItems: 'center',
      backgroundColor: colors.primarySoft,
      borderRadius: 15,
      height: 38,
      justifyContent: 'center',
      marginRight: 11,
      width: 38,
    },
    supplementIconDanger: {
      backgroundColor: colors.surface,
    },
    supplementTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '900',
    },
    supplementTitleDanger: {
      color: colors.danger,
    },
    root: {
      paddingBottom: 4,
    },
  });
}
